import BSVKeys
import BSVWallet
import Foundation
import XCTest
@testable import OneSatActions

final class WalletMetadataCITests: XCTestCase {
    func test_plaintextPassesThroughAndParsesCanonicalFields() async throws {
        let plaintext = "{\"name\":\"Ape\",\"collection\":\"abc_0\"}"
        let fields = try await WalletMetadataCI.load(plaintext) { _ in
            XCTFail("plaintext must not decrypt")
            throw WalletMetadataCI.Error.invalidJSON
        }

        XCTAssertEqual(fields?.plaintext, plaintext)
        XCTAssertEqual(fields?.name, "Ape")
        XCTAssertEqual(fields?.collection, "abc_0")
    }

    func test_encryptedCustomInstructionsDecryptWithWPMFraming() async throws {
        let wallet = ProtoWallet(rootKey: try ActionVectors.identity())
        let plaintext = "{\"name\":\"Encrypted Ape\",\"collection\":\"abc_0\"}"
        let encrypted = try await wallet.encrypt(
            WalletEncryptRequest(
                protocolID: .walletMetadataEncryption,
                keyID: try WalletKeyID("1"),
                counterparty: .self,
                plaintext: Array(plaintext.utf8)
            )
        )
        let base64 = Data(encrypted.ciphertext).base64EncodedString()

        let fields = try await WalletMetadataCI.load(base64) {
            try await wallet.decrypt($0)
        }

        XCTAssertEqual(fields?.plaintext, plaintext)
        XCTAssertEqual(fields?.name, "Encrypted Ape")
        XCTAssertEqual(fields?.collection, "abc_0")
    }

    func test_doubleAndTripleEncryptedCustomInstructionsArePeeled() async throws {
        let wallet = ProtoWallet(rootKey: try ActionVectors.identity())
        let plaintext = "{\"name\":\"Layered Ape\",\"collection\":\"abc_0\"}"

        for layerCount in 2...3 {
            let ciphertext = try await encrypt(
                plaintext,
                layerCount: layerCount,
                wallet: wallet
            )
            let fields = try await WalletMetadataCI.load(ciphertext) {
                try await wallet.decrypt($0)
            }

            XCTAssertEqual(fields?.plaintext, plaintext)
            XCTAssertEqual(fields?.name, "Layered Ape")
            XCTAssertEqual(fields?.collection, "abc_0")
        }
    }

    func test_undecryptableMetadataIsPreserved() async throws {
        let ciphertext = "dW5rbm93bg=="
        let fields = try await WalletMetadataCI.load(ciphertext) { _ in
            throw WalletMetadataCI.Error.invalidJSON
        }

        XCTAssertEqual(fields?.plaintext, ciphertext)
        XCTAssertNil(fields?.name)
        XCTAssertNil(fields?.collection)
    }

    func test_oversizedCiphertextAndPlaintextArePreserved() async throws {
        let limits = WalletCryptoLimits.standard
        let encodedLimit = ((limits.maximumCiphertextByteCount + 2) / 3) * 4
        let oversizedCiphertext = String(repeating: "A", count: encodedLimit + 1)
        let ciphertextFields = try await WalletMetadataCI.load(oversizedCiphertext) { _ in
            XCTFail("oversized ciphertext must not decrypt")
            return WalletDecryptResult(plaintext: [])
        }
        XCTAssertEqual(ciphertextFields?.plaintext, oversizedCiphertext)

        let current = Data([0]).base64EncodedString()
        let oversizedPlaintext = [UInt8](
            repeating: 0x61,
            count: limits.maximumPayloadByteCount + 1
        )
        let plaintextFields = try await WalletMetadataCI.load(current) { _ in
            WalletDecryptResult(plaintext: oversizedPlaintext)
        }
        XCTAssertEqual(plaintextFields?.plaintext, current)
    }

    func test_liveTypeScriptWPMCiphertextFixtureDecrypts() async throws {
        let wallet = ProtoWallet(
            rootKey: try PrivateKey([UInt8](repeating: 0, count: 31) + [42])
        )
        // Generated by live `1sat-sdk` `encryptWalletMetadataCi` with
        // `new ProtoWallet(new PrivateKey(42))`.
        let ciphertext = "H2qN7OsQFp/+gsVE4o5Vnxe+3tamiSrPquahkrphkusHM0phnDiDmYuzVv9flenOq3SszLaoZjvCkkm3FFtddDwu1FwieM95zjBSWUl5PoNk/n2A5Dx8f0XahSTrcQ=="

        let fields = try await WalletMetadataCI.load(ciphertext) {
            try await wallet.decrypt($0)
        }

        XCTAssertEqual(fields?.plaintext, "{\"name\":\"TS Fixture Ape\",\"collection\":\"abc_0\"}")
        XCTAssertEqual(fields?.name, "TS Fixture Ape")
        XCTAssertEqual(fields?.collection, "abc_0")
    }

    private func encrypt(
        _ plaintext: String,
        layerCount: Int,
        wallet: ProtoWallet
    ) async throws -> String {
        var current = plaintext
        for _ in 0..<layerCount {
            let encrypted = try await wallet.encrypt(
                WalletEncryptRequest(
                    protocolID: .walletMetadataEncryption,
                    keyID: try WalletKeyID("1"),
                    counterparty: .self,
                    plaintext: Array(current.utf8)
                )
            )
            current = Data(encrypted.ciphertext).base64EncodedString()
        }
        return current
    }
}
